<?php

  if( function_exists('acf_add_local_field_group') ):

  acf_add_local_field_group(array (
  'key' => 'group_59cad079d8876',
  'title' => 'Bulletin',
  'fields' => array (
    array (
      'key' => 'field_59cad07ea1693',
      'label' => 'Send to:',
      'name' => 'send_to',
      'type' => 'select',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'everyone' => 'Everyone',
        'admin_only' => 'Only those with Admin access',
        'specific_emps' => 'Specific Employees',
      ),
      'default_value' => array (
        0 => 'everyone',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'return_format' => 'value',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_59cad0dca1694',
      'label' => 'These employees:',
      'name' => 'rec_picker',
      'type' => 'user',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_59cad07ea1693',
            'operator' => '==',
            'value' => 'specific_emps',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'role' => '',
      'allow_null' => 0,
      'multiple' => 0,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'bulletin',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array (
    0 => 'permalink',
  ),
  'active' => 1,
  'description' => '',
  ));

  acf_add_local_field_group(array (
  'key' => 'group_59c29d5879b66',
  'title' => 'Dashboard',
  'fields' => array (
    array (
      'key' => 'field_59c2db5a813bf',
      'label' => 'Clocked in Employees',
      'name' => 'clocked_in_employees',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => '',
      'sub_fields' => array (
        array (
          'key' => 'field_59c2dbbb813c0',
          'label' => 'Clocked in Employee',
          'name' => 'clocked_in_employee',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array (
          'key' => 'field_59c2dbcf813c1',
          'label' => 'Clocked in Employee PIN',
          'name' => 'clocked_in_employee_pin',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array (
          'key' => 'field_59c2dbe0813c2',
          'label' => 'Current Timestamp ID',
          'name' => 'current_timestamp_id',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array (
          'key' => 'field_59c2e03f813c4',
          'label' => 'Current Session Clock In Time',
          'name' => 'current_clock_in_time',
          'type' => 'time_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'g:i a',
          'return_format' => 'g:i a',
        ),
        array (
          'key' => 'field_59c496a912465',
          'label' => 'clock in hour',
          'name' => 'clock_in_hour',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ),
        array (
          'key' => 'field_59c496df12466',
          'label' => 'clock in minute',
          'name' => 'clock_in_minute',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'page',
        'operator' => '==',
        'value' => '11',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array (
    0 => 'the_content',
  ),
  'active' => 1,
  'description' => '',
  ));

  acf_add_local_field_group(array (
  'key' => 'group_59c598f25fe15',
  'title' => 'Employees',
  'fields' => array (
    array (
      'key' => 'field_59c5ca263e7f1',
      'label' => 'Display Name',
      'name' => 'display_name',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_59d4805cb7c89',
      'label' => 'Picture',
      'name' => 'picture',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'medium',
      'library' => 'uploadedTo',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_59d4808cb7c8a',
      'label' => 'Phone',
      'name' => 'phone',
      'type' => 'number',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array (
      'key' => 'field_59d4816cb7c8b',
      'label' => 'Email',
      'name' => 'email',
      'type' => 'email',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    array (
      'key' => 'field_59c59909bca46',
      'label' => 'PIN Number',
      'name' => 'employee_pin',
      'type' => 'number',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'min' => 1000,
      'max' => 9999,
      'step' => '',
    ),
    array (
      'key' => 'field_59c5992dbca47',
      'label' => 'Is Clocked In',
      'name' => 'is_clocked_in',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
      'ui' => 0,
      'ui_on_text' => '',
      'ui_off_text' => '',
    ),
    array (
      'key' => 'field_59c5c80675f52',
      'label' => 'Has Admin Access',
      'name' => 'has_timesheet_access',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
      'ui' => 0,
      'ui_on_text' => '',
      'ui_off_text' => '',
    ),
    array (
      'key' => 'field_59c59987bca48',
      'label' => 'Timesheet',
      'name' => 'timesheet',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => 'field_59c599c2bca4a',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => 'Add Shift',
      'sub_fields' => array (
        array (
          'key' => 'field_59c599a0bca49',
          'label' => 'ID',
          'name' => 'id',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array (
          'key' => 'field_59c599c2bca4a',
          'label' => 'Date',
          'name' => 'date',
          'type' => 'date_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'm/d/Y',
          'return_format' => 'm/d/Y',
          'first_day' => 1,
        ),
        array (
          'key' => 'field_59c59a06bca4b',
          'label' => 'Clocked In',
          'name' => 'clocked_in',
          'type' => 'time_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'g:i a',
          'return_format' => 'g:i a',
        ),
        array (
          'key' => 'field_59c59a31bca4c',
          'label' => 'Clocked Out',
          'name' => 'clocked_out',
          'type' => 'time_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'g:i a',
          'return_format' => 'g:i a',
        ),
        array (
          'key' => 'field_59c59a45bca4d',
          'label' => 'Hours',
          'name' => 'hours',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ),
        array (
          'key' => 'field_59c59a5abca4e',
          'label' => 'Minutes',
          'name' => 'minutes',
          'type' => 'number',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'min' => '',
          'max' => '',
          'step' => '',
        ),
      ),
    ),
    array (
      'key' => 'field_59c69e048e2e5',
      'label' => 'Requests',
      'name' => 'requests',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => 'New Request',
      'sub_fields' => array (
        array (
          'key' => 'field_59c69ed68e2e9',
          'label' => 'Request Type',
          'name' => 'req_type',
          'type' => 'select',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array (
            'req_type_off' => 'Can\'t work',
            'req_type_work' => 'Want to work',
          ),
          'default_value' => array (
          ),
          'allow_null' => 0,
          'multiple' => 0,
          'ui' => 0,
          'ajax' => 0,
          'return_format' => 'value',
          'placeholder' => '',
        ),
        array (
          'key' => 'field_59c69e118e2e6',
          'label' => 'From',
          'name' => 'req_date_from',
          'type' => 'date_time_picker',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'm/d/Y g:i a',
          'return_format' => 'D d | h:i a F',
          'first_day' => 1,
        ),
        array (
          'key' => 'field_59c69e4e8e2e7',
          'label' => 'To',
          'name' => 'req_date_to',
          'type' => 'date_time_picker',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'm/d/Y g:i a',
          'return_format' => 'D d | h:i a F',
          'first_day' => 1,
        ),
        array (
          'key' => 'field_59c69eb08e2e8',
          'label' => 'Notes',
          'name' => 'req_notes',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
      ),
    ),
    array (
      'key' => 'field_59c7e074a4de8',
      'label' => 'Time ID',
      'name' => 'time_id',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_59c5992dbca47',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'user_form',
        'operator' => '==',
        'value' => 'all',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array (
    0 => 'the_content',
  ),
  'active' => 1,
  'description' => '',
  ));

  acf_add_local_field_group(array (
  'key' => 'group_59d3a2cf6ad53',
  'title' => 'Weekly Schedule',
  'fields' => array (
    array (
      'key' => 'field_59d3a2cf72b0f',
      'label' => 'Tue Date',
      'name' => 'tue_date',
      'type' => 'date_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'display_format' => 'm/d',
      'return_format' => 'j',
      'first_day' => 1,
    ),
    array (
      'key' => 'field_59d3a2cf72b3a',
      'label' => 'Tue Shifts',
      'name' => 'tue_shifts',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => 'Add Shift',
      'sub_fields' => array (
        array (
          'key' => 'field_59d3a2cf75974',
          'label' => 'Employee',
          'name' => 'employee',
          'type' => 'user',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'role' => '',
          'allow_null' => 0,
          'multiple' => 0,
        ),
        array (
          'key' => 'field_59d3a2cf7598a',
          'label' => 'From',
          'name' => 'from_time',
          'type' => 'time_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'g:i a',
          'return_format' => 'g:i a',
        ),
        array (
          'key' => 'field_59d3a2cf7599b',
          'label' => 'To',
          'name' => 'to_time',
          'type' => 'time_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'g:i a',
          'return_format' => 'g:i a',
        ),
      ),
    ),
    array (
      'key' => 'field_59d3a2cf72b5d',
      'label' => 'Wed Date',
      'name' => 'wed_date',
      'type' => 'date_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'display_format' => 'm/d',
      'return_format' => 'j',
      'first_day' => 1,
    ),
    array (
      'key' => 'field_59d3a2cf72b6d',
      'label' => 'Wed Shifts',
      'name' => 'wed_shifts',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => 'Add Shift',
      'sub_fields' => array (
        array (
          'key' => 'field_59d3a2cf807ea',
          'label' => 'Employee',
          'name' => 'employee',
          'type' => 'user',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'role' => '',
          'allow_null' => 0,
          'multiple' => 0,
        ),
        array (
          'key' => 'field_59d3a2cf807fe',
          'label' => 'From',
          'name' => 'from_time',
          'type' => 'time_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'g:i a',
          'return_format' => 'g:i a',
        ),
        array (
          'key' => 'field_59d3a2cf8080e',
          'label' => 'To',
          'name' => 'to_time',
          'type' => 'time_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'g:i a',
          'return_format' => 'g:i a',
        ),
      ),
    ),
    array (
      'key' => 'field_59d3a2cf72b83',
      'label' => 'Thu Date',
      'name' => 'thu_date',
      'type' => 'date_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'display_format' => 'm/d',
      'return_format' => 'j',
      'first_day' => 1,
    ),
    array (
      'key' => 'field_59d3a2cf72ba5',
      'label' => 'Thu Shifts',
      'name' => 'thu_shifts',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => 'Add Shift',
      'sub_fields' => array (
        array (
          'key' => 'field_59d3a2cf8a9d9',
          'label' => 'Employee',
          'name' => 'employee',
          'type' => 'user',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'role' => '',
          'allow_null' => 0,
          'multiple' => 0,
        ),
        array (
          'key' => 'field_59d3a2cf8a9ee',
          'label' => 'From',
          'name' => 'from_time',
          'type' => 'time_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'g:i a',
          'return_format' => 'g:i a',
        ),
        array (
          'key' => 'field_59d3a2cf8aa0d',
          'label' => 'To',
          'name' => 'to_time',
          'type' => 'time_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'g:i a',
          'return_format' => 'g:i a',
        ),
      ),
    ),
    array (
      'key' => 'field_59d3a2cf72bbf',
      'label' => 'Fri Date',
      'name' => 'fri_date',
      'type' => 'date_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'display_format' => 'm/d',
      'return_format' => 'j',
      'first_day' => 1,
    ),
    array (
      'key' => 'field_59d3a2cf72bda',
      'label' => 'Fri Shifts',
      'name' => 'fri_shifts',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => 'Add Shift',
      'sub_fields' => array (
        array (
          'key' => 'field_59d3a2cf94d9e',
          'label' => 'Employee',
          'name' => 'employee',
          'type' => 'user',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'role' => '',
          'allow_null' => 0,
          'multiple' => 0,
        ),
        array (
          'key' => 'field_59d3a2cf94dbc',
          'label' => 'From',
          'name' => 'from_time',
          'type' => 'time_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'g:i a',
          'return_format' => 'g:i a',
        ),
        array (
          'key' => 'field_59d3a2cf94dd6',
          'label' => 'To',
          'name' => 'to_time',
          'type' => 'time_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'g:i a',
          'return_format' => 'g:i a',
        ),
      ),
    ),
    array (
      'key' => 'field_59d3a2cf72bf2',
      'label' => 'Sat Date',
      'name' => 'sat_date',
      'type' => 'date_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'display_format' => 'm/d',
      'return_format' => 'j',
      'first_day' => 1,
    ),
    array (
      'key' => 'field_59d3a2cf72c02',
      'label' => 'Sat Shifts',
      'name' => 'sat_shifts',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'table',
      'button_label' => 'Add Shift',
      'sub_fields' => array (
        array (
          'key' => 'field_59d3a2cf9f640',
          'label' => 'Employee',
          'name' => 'employee',
          'type' => 'user',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'role' => '',
          'allow_null' => 0,
          'multiple' => 0,
        ),
        array (
          'key' => 'field_59d3a2cf9f655',
          'label' => 'From',
          'name' => 'from_time',
          'type' => 'time_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'g:i a',
          'return_format' => 'g:i a',
        ),
        array (
          'key' => 'field_59d3a2cf9f665',
          'label' => 'To',
          'name' => 'to_time',
          'type' => 'time_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'g:i a',
          'return_format' => 'g:i a',
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'weekly_schedule',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
  ));

endif;?>
